[package]
name = "noir"
version = "0.1.0"
authors = ["Mihir Laud <mihirlaud@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = "0.3"
legion = { version = "0.4.0", default-features = false, features = ["wasm-bindgen"]}