pub const SCREEN_WIDTH: i32 = 100;
pub const SCREEN_HEIGHT: i32 = 60;

pub const MAP_WIDTH: i32 = 85;
pub const MAP_HEIGHT: i32 = 45;

pub const SIDEBAR_WIDTH: i32 = SCREEN_WIDTH - MAP_WIDTH;
pub const SIDEBAR_HEIGHT: i32 = MAP_HEIGHT;

pub const LOG_WIDTH: i32 = SCREEN_WIDTH;
pub const LOG_HEIGHT: i32 = SCREEN_HEIGHT - MAP_HEIGHT;

pub const TALK_PANEL_WIDTH: i32 = MAP_WIDTH;
pub const TALK_PANEL_HEIGHT: i32 = MAP_HEIGHT;
